query Stations {
  stationInformation {
    data {
      stations {
        capacity
        address
        lat
        lon
        name
        shortName
        stationId
      }
    }
  }
  stationStatus {
    data {
      stations {
        numBikesAvailable
        numDocksAvailable
        stationId
      }
    }
  }
}
