# Serve the api gateway with next.js
# @see https://the-guild.dev/graphql/mesh/docs/getting-started/deploy-mesh-gateway#deploy-mesh-on-vercel-with-nextjs-api-routes
serve:
  endpoint: /api/graphql

require:
  # Get the env variables
  - dotenv/config

sources:
  # GBFS api
  # @see https://transport.data.gouv.fr/gbfs/rouen
  # @see https://github.com/MobilityData/gbfs-json-schema/tree/master/v1.1
  - name: Gbfs
    handler:
      jsonSchema:
        endpoint: 'https://transport.data.gouv.fr/gbfs/rouen'
        operations:
          - type: Query
            field: gbfs
            path: /gbfs.json
            method: GET
            responseSchema: ./src/services/gbfs/gbfs.json
          - type: Query
            field: systemInformation
            path: /system_information.json
            method: GET
            responseSchema: ./src/services/gbfs/system_information.json
          - type: Query
            field: stationStatus
            path: /station_status.json
            method: GET
            responseSchema: ./src/services/gbfs/station_status.json
          - type: Query
            field: stationInformation
            path: /station_information.json
            method: GET
            responseSchema: ./src/services/gbfs/station_information.json
    transforms:
      - namingConvention:
          mode: wrap
          typeNames: pascalCase
          enumValues: pascalCase
          fieldNames: camelCase
          fieldArgumentNames: camelCase
  # OpenWeather api
  # @see https://openweathermap.org/api
  - name: OpenWeather
    handler:
      jsonSchema:
        endpoint: https://api.openweathermap.org/data/2.5
        queryParams:
          appid: '{env.OPEN_WEATHER_API_KEY}'
          mode: 'json'
          unit: 'metric'
        operations:
          - type: Query
            field: weather
            path: /weather
            method: GET
            responseSample: ./src/services/openWeather/weather.response.json
            argTypeMap:
              lat:
                type: string
              lon:
                type: string
            queryParamArgMap:
              lat: lat
              lon: lon
    transforms:
      - rename:
          mode: wrap
          renames:
            - from:
                type: query_weather_rain
                field: _1h
              to:
                type: query_weather_rain
                field: nextHour
      - namingConvention:
          mode: wrap
          typeNames: pascalCase
          enumValues: pascalCase
          fieldNames: camelCase
          fieldArgumentNames: camelCase
