name: Sync preview branch
on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: ⚙️ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⚙️ Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: ⚙️ Fetch all branches
        run: git fetch --all

      - name: ⚙️ Create or overwrite the 'feature/syncing-test' branch
        run: |
          git checkout main
          git branch -f feature/syncing-test

      - name: ⚙️ Push 'feature/syncing-test' branch to remote
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin feature/syncing-test --force
